import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import SessionClientProvider from "@/components/SessionClientProvider";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const interSans = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionClientProvider>
      <NuqsAdapter>
        <html lang="en">
          <body className={`${interSans.className} antialiased`}>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </body>
        </html>
      </NuqsAdapter>
    </SessionClientProvider>
  );
}
